### ISSUE TITLE
Wake word acknowledgment chirp is not muted while asleep (Desktop)

### ISSUE THREAD

**Issue by evan-goode** [MycroftAI/skill-naptime#7]
I'm not sure whether this is intended functionality, but when Mycroft is sleeping, I still hear chirps when I say "hey, Mycroft." I would like to use the naptime skill to temporarily mute all of Mycroft's sounds, including the chirp, and only have it wake up and make noise again once I say "hey Mycroft, wake up."

**Comment by forslund** [comment]
Is this on a mark-1 or desktop? On the mark-1 and picroft this is true (performs a global mute) but not on the desktop.

**Comment by evan-goode** [comment]
I'm on desktop. I don't want to mute the whole system (I see that problem was addressed in another issue), just the chirp.

**Comment by hariedo** [comment]
It seems on Picroft that there is still a very small chirp if it hears the wake word.  (Version as of 0.9.16 Mycroft 2018-02-05.)  This seems acceptable to me, as it helps me confirm it is ready to hear the "wake up" command (as there are no enclosure LEDs to flash).  However, I could see that some people would want it 100% silenced.

**Comment by brezuicabogdan** [comment]
Related to this I am running Mycroft on Linux (Ubuntu 18.08 LTS) and it seems the volume is not muted at all. The main 'annoyance' is that I want to use Mycroft for notifications also and even when sleeping mycroft speaks if for example I manually execute the mycroft-speak bash command or manually send a message via the Bus.

I don't know if this is intentional or not because I see some Bus messages in teh skill that (I think) are supposed to mute the system but what I would propose is have a setting for the naptime skill that would enable or disable muting or volume lowering when going to sleep and maybe have aanothe rsetting setting the value of the lowered volume.

This would allow desktop users to disable volume lowering or muting altogether but still allow users like me (on LInux) to set the volume Mycroft should use when sleeping.

Thank you.

**Comment by forslund** [comment]
The muting of audio output is currently only enabled on the picroft and Mycroft Mark-1. We're using a bit of a heavyhanded approach muting the master sound device for those devices and it's not really a good way of handling it on a desktop.

We will implement a better method of doing this for PC hopefully in the coming months.

**Comment by brezuicabogdan** [comment]
Thank you @forslund. I am running on a Linux server not really a desktop and since Mycroft is the only service using audio on the server I will try to force the picroft volume mutting until a better solution becomes available.

**Comment by Izzette** [comment]
@forslund any traction on this, are you looking for help?

**Comment by krisgesling** [comment]
Hi @Izzette, this hasn't been looked at as far as I know. 

If you are interested in looking into better ways to handle this that would be excellent :)

**Comment by krisgesling** [comment]
This is now live in the Marketplace version of the Skill. 

Closing the issue but please let us know if you continue to experience it.
